name: Run Noor Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pyTelegramBotAPI

      - name: Execute Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
